name: Sync Issues

on:
  workflow_dispatch:
  push:
    branches:
      - development
  schedule:
    - cron: "15 * * * *" # every hour at minute 15 (github recommends to set such cron jobs not at the start of an hour)


jobs:
  sync-issues:
    name: Sync Issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"

      - name: Yarn Install
        run: yarn install --mode=skip-build

      - name: Get GitHub App token
        uses: tibdex/github-app-token@v1.7.0
        id: get_installation_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Sync Issues
        env:
          ARTIFACT_CONTENTS: ${{ steps.download-artifact.outputs.artifact_content }}
          DEVPOOL_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Or your GitHub API token
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          set -e
          ARTIFACT_CONTENTS=$(actions/download-artifact@v2 --name twitterMap || echo "Artifact not found.")
          if [ "$ARTIFACT_CONTENTS" == "Artifact not found." ]; then
            exit 0
          fi
          npx tsx index.ts "$ARTIFACT_CONTENTS"