name: Sync Issues

on:
  push:
    branches:
      - development
  schedule:
    - cron: "15 * * * *" # every hour at minute 15 (github recommends to set such cron jobs not at the start of an hour)
  workflow_dispatch:


jobs:
  sync-issues:
    name: Sync Issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"

      - name: Yarn Install
        run: yarn install --mode=skip-build

      - name: Get GitHub App token
        uses: tibdex/github-app-token@v1.7.0
        id: get_installation_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}


      # - name: Check if Artifact Exists
      #   id: check_artifact
      #   run: |
      #     if [ -d "$GITHUB_WORKSPACE/twitterMap" ]; then
      #       echo "Artifact exists."
      #       echo ::set-output name=artifact_exists::true
      #     else
      #       echo "Artifact does not exist."
      #       echo ::set-output name=artifact_exists::false
      #     fi

      - name: Download Artifact
        # if: steps.check_artifact.outputs.artifact_exists == 'true'
        uses: actions/download-artifact@v4
        with:
          name: twitterMap

      - name: Sync Issues
        env:
          ARTIFACT_CONTENTS: ${{ steps.download-artifact.outputs.artifact_content }}
          DEVPOOL_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Or your GitHub API token
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: echo "{a:1}" > twitterMap.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: twitterMap
          path: twitterMap.json